### ISSUE TITLE
move this example to the module

### ISSUE THREAD

**Issue by npalm** [philips-labs/thanos-on-hsdp#1]
For terraform modules it is quite common to add examples in an examples directory in the module. Those examples are also shown in the terraform module registry. Maybe an good idea for this example as well? Shall I open a PR?

**Comment by loafoe** [comment]
@npalm the module already has an example folder:

https://github.com/philips-labs/terraform-cloudfoundry-thanos/tree/main/examples/default

Feel free to improve on it though e.g. the `README.md` is missing I see :)

We point customers to this repository as an almost-ready-to-use-root-module for quickly trying out the capability.
